function F = residual_db(   D, ...
                            k_on, ...
                            k_off, ...
                            mobile_fraction, ...
                            intensity_inside_bleach_region, ...
                            intensity_outside_bleach_region, ...
                            x_bleach, ...
                            y_bleach, ...
                            r_bleach, ...
                            delta_t, ...
                            number_of_pixels, ...
                            number_of_images, ...
                            number_of_pad_pixels, ...
                            data)

model = signal_db(  D, ...
                    k_on, ...
                    k_off, ...
                    mobile_fraction, ...
                    intensity_inside_bleach_region, ...
                    intensity_outside_bleach_region, ...
                    x_bleach, ...
                    y_bleach, ...
                    r_bleach, ...
                    delta_t, ...
                    number_of_pixels, ...
                    number_of_images, ...
                    number_of_pad_pixels);

F = model(:) - data(:);

end

