function F = residual_recoverycurve_diffusion_and_binding_full( D, ...
                                                                k_on, ...
                                                                k_off, ...
                                                                mobile_fraction, ...
                                                                x_bleach, ...
                                                                y_bleach, ...
                                                                r_bleach, ...
                                                                intensity_inside_bleach_region, ...
                                                                intensity_outside_bleach_region, ...
                                                                delta_t, ...
                                                                number_of_time_points_fine_per_coarse, ...
                                                                number_of_pad_pixels, ...
                                                                image_data_post_bleach)

[number_of_pixels, ~, number_of_post_bleach_images] = size(image_data_post_bleach);

image_data_post_bleach_model = signal_diffusion_and_binding(D, ...
                                                            k_on, ...
                                                            k_off, ...
                                                            mobile_fraction, ...
                                                            x_bleach, ...
                                                            y_bleach, ...
                                                            r_bleach, ...
                                                            intensity_inside_bleach_region, ...
                                                            intensity_outside_bleach_region, ...
                                                            delta_t, ...
                                                            number_of_time_points_fine_per_coarse, ...
                                                            number_of_pixels, ...
                                                            number_of_post_bleach_images, ...
                                                            number_of_pad_pixels);

[X, Y] = meshgrid(1:number_of_pixels, 1:number_of_pixels);
X = X - 0.5;
Y = Y - 0.5;
ind = find( (X - x_bleach).^2 + (Y - y_bleach).^2 <= r_bleach^2 );
ind = ind(:);

recovery_curve = zeros(1, number_of_post_bleach_images);
for current_image_post_bleach = 1:number_of_post_bleach_images
    slice = image_data_post_bleach(:, :, current_image_post_bleach);
    recovery_curve(current_image_post_bleach) = mean(slice(ind));
end

recovery_curve_model = zeros(1, number_of_post_bleach_images);
for current_image_post_bleach = 1:number_of_post_bleach_images
    slice = image_data_post_bleach_model(:, :, current_image_post_bleach);
    recovery_curve_model(current_image_post_bleach) = mean(slice(ind));
end

F = recovery_curve_model(:) - recovery_curve(:);

end

