function F = residual_diffusion_and_binding_2(  mobile_fraction, ...
                                                intensity_inside_bleach_region, ...
                                                intensity_outside_bleach_region, ...
                                                image_data_post_bleach, ...
                                                image_data_post_bleach_model_unscaled, ...
                                                initial_condition_model_unscaled)

image_data_post_bleach_model_unscaled = 2 * (intensity_outside_bleach_region - intensity_inside_bleach_region) * ( mobile_fraction * image_data_post_bleach_model_unscaled + (1 - mobile_fraction) * initial_condition_model_unscaled ) + 2 * intensity_inside_bleach_region - intensity_outside_bleach_region;

F = image_data_post_bleach_model_unscaled(:) - image_data_post_bleach(:);

end

