%% Initialization.
clear
clc
close all hidden

%% Experiment parameters.
delta_t = 0.25; % s
number_of_post_bleach_images = 40;
number_of_pixels = 256;
number_of_pad_pixels = 128;
r_bleach = 32; % pixels
x_bleach = 128;
y_bleach = 128;
intensity_inside_bleach_region = 0.6;
intensity_outside_bleach_region = 0.9;

number_of_time_points_fine_per_coarse = [];

%% Particle parameters.
D = 200; % pixels^2 / s
k_on = 0.1; % 1/s
k_off = 1.0; % 1/s
mobile_fraction = 1.0;%0.8;

%% Simulate true data set.
image_data_post_bleach_true = signal_diffusion_and_binding(  D, ...
                                                        k_on, ...
                                                        k_off, ...
                                                        mobile_fraction, ...
                                                        x_bleach, ...
                                                        y_bleach, ...
                                                        r_bleach, ...
                                                        intensity_inside_bleach_region, ...
                                                        intensity_outside_bleach_region, ...
                                                        delta_t, ...
                                                        number_of_time_points_fine_per_coarse, ...
                                                        number_of_pixels, ...
                                                        number_of_post_bleach_images, ...
                                                        number_of_pad_pixels);

%% Sweep parameters.
number_of_grid_points = 4+3*3;
[K_ON, K_OFF] = ndgrid(logspace(-2, 1, number_of_grid_points), logspace(-2, 1, number_of_grid_points));
SS = zeros(number_of_grid_points, number_of_grid_points);

for i = 1:number_of_grid_points^2
    disp(i/number_of_grid_points^2)
    image_data_post_bleach_model = signal_diffusion_and_binding(D, ...
                                                                K_ON(i), ...
                                                                K_OFF(i), ...
                                                                mobile_fraction, ...
                                                                x_bleach, ...
                                                                y_bleach, ...
                                                                r_bleach, ...
                                                                intensity_inside_bleach_region, ...
                                                                intensity_outside_bleach_region, ...
                                                                delta_t, ...
                                                                number_of_time_points_fine_per_coarse, ...
                                                                number_of_pixels, ...
                                                                number_of_post_bleach_images, ...
                                                                number_of_pad_pixels);
    SS(i) = sum( ( image_data_post_bleach_model(:) - image_data_post_bleach_true(:) ).^2 );
end

%SS(SS==0) = 1e-
figure, hold on
surf(log10(K_ON), log10(K_OFF), log10(SS))