%% Initialization.
clear
clc
close all hidden

%% Parameters.
D_SI = 2.5e-10; % m^2/s
pixel_size = 7.5e-07; % m
D = D_SI / pixel_size^2; % pixels^2 / s
k_on = 0.5; % 1/s
k_off = 0.5; % 1/s
mobile_fraction = 0.4 * 0.6*rand();%0.90; % dimensionless

delta_t = 0.25; % s.
number_of_time_points_fine_per_coarse = 500; % dimensionless
number_of_pixels = 256;
number_of_post_bleach_images = 10;
number_of_pad_pixels = 128;
x_bleach = number_of_pixels / 2; % pixels
y_bleach = number_of_pixels / 2; % pixels
r_bleach = 32; % pixels
intensity_inside_bleach_region = 0.3 + 0.4 * rand(); % a.u.
intensity_outside_bleach_region = intensity_inside_bleach_region + (1 - intensity_inside_bleach_region) * rand(); % a.u.

%% Simulate.
image_data_post_bleach = signal_diffusion_and_binding(  D, ...
                                                        k_on, ...
                                                        k_off, ...
                                                        mobile_fraction, ...
                                                        x_bleach, ...
                                                        y_bleach, ...
                                                        r_bleach, ...
                                                        intensity_inside_bleach_region, ...
                                                        intensity_outside_bleach_region, ...
                                                        delta_t, ...
                                                        number_of_time_points_fine_per_coarse, ...
                                                        number_of_pixels, ...
                                                        number_of_post_bleach_images, ...
                                                        number_of_pad_pixels);
                                                    
%% Simulate unscaled version which is rescaled afterwards.
[image_data_post_bleach_unscaled, initial_condition] = signal_diffusion_and_binding( D, ...
                                                                            k_on, ...
                                                                            k_off, ...
                                                                            1.0, ...
                                                                            x_bleach, ...
                                                                            y_bleach, ...
                                                                            r_bleach, ...
                                                                            0.5, ...
                                                                            1.0, ...
                                                                            delta_t, ...
                                                                            number_of_time_points_fine_per_coarse, ...
                                                                            number_of_pixels, ...
                                                                            number_of_post_bleach_images, ...
                                                                            number_of_pad_pixels);
                                                                        

image_data_post_bleach_special = 2 * (intensity_outside_bleach_region - intensity_inside_bleach_region) * ( mobile_fraction * image_data_post_bleach_unscaled + (1 - mobile_fraction) * initial_condition ) + 2 * intensity_inside_bleach_region - intensity_outside_bleach_region;

sum(abs(image_data_post_bleach_special(:) - image_data_post_bleach(:)))